[general]
import = [
    "themes/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
dimensions = { columns = 220, lines = 70 }
position = { x = 350, y = 250 }
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless" # Full | None
opacity = 0.8
blur = true
# startup_mode = "SimpleFullscreen"
dynamic_title = true

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "Bold" }
italic = { family = "Liga SFMono Nerd Font", style = "Italic" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
