[general]
import = [
    "themes/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 220, lines = 70 }
position = { x = 350, y = 300 }
decorations = "Buttonless" # Full | None
opacity = 0.8
blur = true
# startup_mode = "SimpleFullscreen"
dynamic_title = true

[font]
normal = { family = "SF Mono", style = "Regular" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
